name: auto_x
description: Application for getting autox classes.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.2
  equatable: ^1.2.3
  bloc: 4.0.0
  flutter_bloc: ^4.0.0
  localstorage: ^2.0.0
  flutter_plugin_pdf_viewer: any
  audioplayers: ^0.16.1
  flutter_launcher_icons: ^0.8.1
  xml2json: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^5.0.0
  mockito: 4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

flutter_icons:
  image_path: "assets/scca_wheel.png"
  ios: true
  android: true